### ISSUE TITLE
Maven test execution fails if specifying test suite

### ISSUE THREAD

**Issue by talmoshe** [reportportal/example-java-junit#1]
I'm using the example in https://github.com/reportportal/example-java-junit

when running the below it's working fine
C:\Users\talm\git\example-java-junit\v4>mvn test

Also the below works fine:
C:\Users\talm\git\example-java-junit\v4>mvn -Dtest=TestIssue4 test

**This execution fails:**
C:\Users\talm\git\example-java-junit\v4>**mvn -Dtest=SimpleTestSuite1 test**

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.epam.rp.tests.SimpleTestSuite1
2018-06-17 14:14:06,265 [main] ERROR com.epam.reportportal.junit.ParallelRunningHandler - Unable start test suite: 'null'
com.epam.reportportal.exception.ReportPortalClientException: Report Portal returned error
Status code: 400
Status message: Bad Request
Error Message: Incorrect Request. [Field 'name' shouldn't be null.]
Error Type: INCORRECT_REQUEST
Stack Trace:
        at com.epam.reportportal.service.ReportPortalErrorHandler.handleClientError(ReportPortalErrorHandler.java:47)
        at com.epam.reportportal.restclient.endpoint.DefaultErrorHandler.handle(DefaultErrorHandler.java:73)

**Comment by talmoshe** [comment]
Duplicated it to agent-java-junit project
